# general settings
name: '006'
# name: DEBUG


model_type: HDRModel
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    name: MatSynthDataset
    type: MatSynthDataset
    svbrdf_root: /home/xiaojiu/datasets/MatSynth/train_OurIndoor_Linear

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 1
    prefetch_mode: cuda
    pin_memory: true

  val:
    name: MatSynthDataset
    type: MatSynthDataset
    svbrdf_root: /home/xiaojiu/datasets/MatSynth/test_linear
    single_input: True

distance: 2.414

brdf_args:
  split_num: 4
  nbRendering: 1
  split_axis: 1
  concat: True
  svbrdf_norm: True
  size: 256
  order: 'ndrs'
  toLDR: True
  lampIntensity: 18

# network structures
network_g:
  type: HDRNet
  img_channel: 6
  width: 32
  enc_blk_nums: [2, 2, 4, 8]
  middle_blk_num: 12
  dec_blk_nums: [2, 2, 2, 2]

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 5e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: TrueCosineAnnealingLR
    T_max: 200000
    eta_min: !!float 1e-6


  total_iter: 200000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1
    reduction: mean

# validation settings 
val:
  val_freq: !!float 1e4

  metrics:
    pix: # metric name, can be arbitrary
      type: calculate_pixel
      weight: 1
    rmse:
      type: calculate_rmse
      weight: 1

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e4
  use_tb_logger: true